In [1]:
import numpy as np
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
torch.__version__

'1.6.0'

# Tensor

In [3]:
x = torch.empty(5, 3)

In [5]:
x = torch.rand(5, 4)

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)

In [9]:
x = torch.tensor([5.5, 3])

In [11]:
x = x.new_ones(5, 3, dtype=torch.double)

In [14]:
x = torch.randn_like(x, dtype=torch.float)

In [19]:
y = torch.rand(5, 3)
print(x+y)

tensor([[ 2.1285,  1.0952,  0.5785],
        [-0.5757,  0.8168, -2.3387],
        [ 0.8517,  0.3733,  1.1096],
        [ 2.0056, -0.7075,  0.2362],
        [-1.3086,  1.6838, -2.1667]])


In [20]:
torch.add(x, y)

tensor([[ 2.1285,  1.0952,  0.5785],
        [-0.5757,  0.8168, -2.3387],
        [ 0.8517,  0.3733,  1.1096],
        [ 2.0056, -0.7075,  0.2362],
        [-1.3086,  1.6838, -2.1667]])

In [21]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)

tensor([[ 2.1285,  1.0952,  0.5785],
        [-0.5757,  0.8168, -2.3387],
        [ 0.8517,  0.3733,  1.1096],
        [ 2.0056, -0.7075,  0.2362],
        [-1.3086,  1.6838, -2.1667]])

In [22]:
result

tensor([[ 2.1285,  1.0952,  0.5785],
        [-0.5757,  0.8168, -2.3387],
        [ 0.8517,  0.3733,  1.1096],
        [ 2.0056, -0.7075,  0.2362],
        [-1.3086,  1.6838, -2.1667]])

In [25]:
y.add_(x)

tensor([[ 2.1285,  1.0952,  0.5785],
        [-0.5757,  0.8168, -2.3387],
        [ 0.8517,  0.3733,  1.1096],
        [ 2.0056, -0.7075,  0.2362],
        [-1.3086,  1.6838, -2.1667]])

In [26]:
y

tensor([[ 2.1285,  1.0952,  0.5785],
        [-0.5757,  0.8168, -2.3387],
        [ 0.8517,  0.3733,  1.1096],
        [ 2.0056, -0.7075,  0.2362],
        [-1.3086,  1.6838, -2.1667]])

In [27]:
x

tensor([[ 1.8137,  0.3680,  0.4661],
        [-1.0909,  0.5258, -2.6541],
        [-0.0175,  0.3569,  0.4584],
        [ 1.7356, -0.9237, -0.1650],
        [-1.9305,  1.3315, -2.2101]])

In [28]:
x[:, 1:]

tensor([[ 0.3680,  0.4661],
        [ 0.5258, -2.6541],
        [ 0.3569,  0.4584],
        [-0.9237, -0.1650],
        [ 1.3315, -2.2101]])

In [30]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [33]:
x[0][0].item()

0.9757257699966431

In [34]:
x

tensor([[ 0.9757,  0.2962,  1.3523,  0.8573],
        [ 0.4896, -1.0693,  0.8528, -1.0210],
        [ 0.4682,  1.1935, -1.1828, -0.8871],
        [ 1.1448,  0.6337,  1.9303, -0.0401]])

In [36]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [38]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [39]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [40]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [41]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [42]:
a

array([2., 2., 2., 2., 2.])

In [43]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [44]:
torch.cuda.is_available()

False

# AutoGrad

In [47]:
x = torch.ones(2, 2, requires_grad=True)

In [48]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [49]:
y = x + 2

In [50]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [52]:
y.grad_fn

In [53]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [56]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad, a)
a.requires_grad_(True)
print(a.requires_grad, a)
b = ( a * a).sum()
print(b.grad_fn)

False tensor([[1.0417, 1.3117],
        [0.5579, 1.9686]])
True tensor([[1.0417, 1.3117],
        [0.5579, 1.9686]], requires_grad=True)


In [57]:
out.backward()

In [58]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [59]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2

In [63]:
y.norm()

tensor(1749.0308, grad_fn=<NormBackward0>)

In [64]:
y

tensor([ -386.1556,  -979.5674, -1396.5815], grad_fn=<MulBackward0>)

In [65]:
v = torch.tensor([0.1, 1.0, 0.0001])
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [68]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [69]:
print(x.requires_grad)
y = x.detach()
print(x.requires_grad)
print(y.requires_grad)
print(x.eq(y).all())

True
True
False
tensor(True)


# Network

In [15]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16*6*6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [16]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [17]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.1184,  0.0300, -0.0072,  0.1165,  0.0094, -0.1136,  0.0572, -0.0353,
          0.0290, -0.0624]], grad_fn=<AddmmBackward>)


In [18]:
net.zero_grad()

In [19]:
out.backward(torch.randn(1, 10))

In [22]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
critertion = nn.MSELoss()
loss = critertion(output, target)
print(loss)

tensor(2.1191, grad_fn=<MseLossBackward>)


In [25]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

In [27]:
net.zero_grad()
print(net.conv1.bias.grad)
loss.backward()
print(net.conv1.bias.grad)

tensor([0., 0., 0., 0., 0., 0.])
tensor([-0.0049,  0.0029,  0.0069,  0.0059,  0.0086,  0.0226])


In [28]:
lr = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * lr)

In [29]:
from torch import optim

In [31]:
opt = optim.SGD(net.parameters(), lr=lr)

opt.zero_grad()
output = net(input)
loss = critertion(output, target)
loss.backward()
opt.step()

In [32]:
target

tensor([[-1.1661,  0.9849, -0.0337, -0.7809,  1.9200, -3.3447, -1.5494,  0.3100,
          1.0164,  0.1787]])

In [33]:
loss

tensor(2.0889, grad_fn=<MseLossBackward>)